import React from 'react';
import { View, Text, TouchableOpacity, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '../theme';

export default function FigmaAuthStatus({ eyebrow, title, icon, tone = 'gold', heading, message, primaryLabel, onPrimary, secondaryLabel, onSecondary, onBack, children }) {
  const accent = tone === 'error' ? '#E45D5D' : colors.purple;
  return <View style={styles.screen}><View style={styles.body}>{(onBack || eyebrow || title) ? <View style={styles.header}>{onBack ? <TouchableOpacity style={styles.back} onPress={onBack}><Ionicons name="chevron-back" size={16} color="#F4F4F5" /></TouchableOpacity> : null}<View style={styles.headerCopy}><Text style={styles.eyebrow}>{eyebrow}</Text><Text style={styles.title}>{title}</Text></View></View> : null}<View style={styles.iconBlock}><View style={[styles.glow, { backgroundColor: accent, shadowColor: accent }]} /><View style={[styles.iconCircle, { borderColor: `${accent}55` }]}><Ionicons name={icon} size={42} color={accent} /></View></View><View style={styles.copy}><Text style={styles.heading}>{heading}</Text><Text style={styles.message}>{message}</Text></View><View style={styles.actions}><TouchableOpacity style={styles.primary} onPress={onPrimary}><Text style={styles.primaryText}>{primaryLabel}</Text></TouchableOpacity>{secondaryLabel ? <TouchableOpacity style={styles.secondary} onPress={onSecondary}><Text style={styles.secondaryText}>{secondaryLabel}</Text></TouchableOpacity> : null}{children}</View></View></View>;
}
const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#080808', justifyContent: 'center' }, body: { paddingHorizontal: 24, gap: 32, alignItems: 'center' }, header: { width: '100%', height: 64, paddingTop: 16, paddingBottom: 8, flexDirection: 'row', alignItems: 'center', gap: 16 }, back: { width: 36, height: 36, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', backgroundColor: '#121212', alignItems: 'center', justifyContent: 'center' }, headerCopy: { flex: 1 }, eyebrow: { color: '#A1A1AA', fontSize: 11, fontWeight: '500' }, title: { color: '#F4F4F5', fontSize: 22, fontWeight: '600', marginTop: 2 }, iconBlock: { width: 120, height: 120, alignItems: 'center', justifyContent: 'center' }, glow: { position: 'absolute', width: 1, height: 1, borderRadius: 1, shadowOpacity: 0.4, shadowRadius: 48, shadowOffset: { width: 0, height: 0 } }, iconCircle: { width: 82, height: 82, borderRadius: 41, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, copy: { gap: 12, alignItems: 'center' }, heading: { color: '#F4F4F5', fontSize: 20, fontWeight: '600', textAlign: 'center' }, message: { color: '#A1A1AA', fontSize: 14, lineHeight: 21, textAlign: 'center' }, actions: { width: '100%', gap: 12 }, primary: { height: 48, borderRadius: 14, backgroundColor: colors.purple, alignItems: 'center', justifyContent: 'center' }, primaryText: { color: '#080808', fontSize: 14, fontWeight: '600' }, secondary: { height: 48, borderRadius: 14, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', alignItems: 'center', justifyContent: 'center' }, secondaryText: { color: '#F4F4F5', fontSize: 14, fontWeight: '600' },
});
