import React, { useEffect, useState } from 'react';
import { View, Text, Image, TouchableOpacity, StyleSheet, ScrollView } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '../theme'; import RegistryHeader from '../components/RegistryHeader';
import { getCardById, getSetById, CARD_DETAIL } from '../data'; import { getLiveSetValuations } from '../lib/liveSetValuation';
export default function CardDetailScreen({ navigate, goBack, params={}, collectionQuantities={}, addRequirementsToWishlist=()=>{} }) {
 const card=getCardById(params.cardId||CARD_DETAIL.id,CARD_DETAIL); const set=getSetById(card.setId,null); const owned=Number(collectionQuantities[card.id]||0)>0; const [price,setPrice]=useState(null);
 useEffect(()=>{let active=true;if(set)getLiveSetValuations(set).then((v)=>{if(!active)return;const maps=Object.values(v?.valuations||{}).map(t=>t.requirementPrices||{});const hit=maps.map(m=>m[card.id]).find(x=>Number.isFinite(Number(x)));setPrice(hit==null?null:Number(hit));}).catch(()=>setPrice(null));return()=>{active=false};},[card.id,set?.id]);
 return <View style={styles.page}><RegistryHeader title="Card Details" onBack={goBack} onSearch={()=>navigate('Search')} /><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
  <TouchableOpacity style={styles.artWrap} onPress={()=>navigate('CardZoom',{cardId:card.id})}><Image source={{uri:card.image}} style={styles.art} resizeMode="contain" /></TouchableOpacity>
  <Text style={styles.kicker}>{String(set?.name||card.setName||'SET').toUpperCase()} · #{card.number||card.localId||'—'}</Text><Text style={styles.name}>{card.name}</Text>
  <View style={styles.chips}><Tag text={card.rarity||'Unknown rarity'} /><Tag text={card.variant||card.finish||'Standard'} /></View>
  <View style={styles.metrics}><Metric label="MARKET PRICE" value={price==null?'Unavailable':`€${price.toFixed(2)}`} sub={price==null?'Provider price unavailable':'Live RapidAPI market'} /><Metric label="OWNED" value={owned?`${collectionQuantities[card.id]} cop${collectionQuantities[card.id]===1?'y':'ies'}`:'Not owned'} sub={owned?'In your registry':'Ready to acquire'} /></View>
  <View style={styles.notes}><Text style={styles.notesTitle}>Collector Notes</Text><Text style={styles.notesText}>{card.description||'Verified collectible printing. Add acquisition details after logging this card.'}</Text></View>
  <TouchableOpacity style={styles.link} onPress={()=>navigate('Variants',{cardId:card.id})}><Text style={styles.linkText}>View all printings</Text><Ionicons name="chevron-forward" color={colors.purple} size={14}/></TouchableOpacity>
 </ScrollView><View style={styles.actions}><TouchableOpacity style={styles.primary} onPress={()=>navigate(owned?'EditOwnedCard':'AddToCollection',{cardId:card.id})}><Text style={styles.primaryText}>{owned?'Edit Owned Card':'Add to Collection'}</Text></TouchableOpacity><TouchableOpacity style={styles.secondary} onPress={()=>addRequirementsToWishlist([card])}><Text style={styles.secondaryText}>Save to Wishlist</Text></TouchableOpacity></View></View>;
}
function Tag({text}){return <View style={styles.tag}><Text style={styles.tagText}>{text}</Text></View>} function Metric({label,value,sub}){return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricSub}>{sub}</Text></View>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.bg,paddingHorizontal:20},content:{paddingBottom:150},artWrap:{height:274,alignItems:'center',justifyContent:'center',marginTop:4},art:{width:200,height:274,borderRadius:8},kicker:{color:colors.purple,fontSize:8,fontWeight:'800',marginTop:12},name:{color:colors.text,fontSize:25,fontWeight:'800',marginTop:4},chips:{flexDirection:'row',gap:7,marginTop:9},tag:{borderWidth:1,borderColor:colors.border,borderRadius:12,paddingHorizontal:9,paddingVertical:5},tagText:{color:colors.textSecondary,fontSize:8},metrics:{flexDirection:'row',gap:8,marginTop:16},metric:{flex:1,backgroundColor:colors.card,borderWidth:1,borderColor:colors.border,borderRadius:10,padding:12},metricLabel:{color:colors.textTertiary,fontSize:7,fontWeight:'700'},metricValue:{color:colors.purple,fontSize:16,fontWeight:'800',marginTop:6},metricSub:{color:colors.textTertiary,fontSize:7,marginTop:3},notes:{backgroundColor:colors.card,borderWidth:1,borderColor:colors.border,borderRadius:10,padding:12,marginTop:10},notesTitle:{color:colors.text,fontSize:9,fontWeight:'700'},notesText:{color:colors.textSecondary,fontSize:8,lineHeight:13,marginTop:6},link:{height:42,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},linkText:{color:colors.purple,fontSize:9,fontWeight:'700'},actions:{position:'absolute',left:20,right:20,bottom:10},primary:{height:47,borderRadius:7,backgroundColor:colors.purple,alignItems:'center',justifyContent:'center'},primaryText:{color:colors.bg,fontSize:11,fontWeight:'800'},secondary:{height:41,borderRadius:7,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center',marginTop:7,backgroundColor:colors.bg},secondaryText:{color:colors.text,fontSize:10,fontWeight:'700'}});
