import React, { useMemo } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { colors } from "../theme";
import CollectionSectionTabs from "../components/CollectionSectionTabs";

const LABELS={"card-added":"Added","card-removed":"Removed","quantity-changed":"Updated quantity for","binder-created":"Created binder","binder-completed":"Completed set","wishlist-acquired":"Acquired","milestone-unlocked":"Unlocked milestone","graded-asset-added":"Added graded asset","sealed-asset-added":"Added sealed asset","graded-asset-removed":"Removed graded asset","sealed-asset-removed":"Removed sealed asset"};
export default function CollectionHistoryScreen({navigate,historyEvents=[]}){
  const events=useMemo(()=>historyEvents.slice().sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp)),[historyEvents]);
  return <ScrollView style={s.page} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <View style={s.heading}><View><Text style={s.title}>Index Timeline</Text><Text style={s.kicker}>ACQUISITION HISTORY</Text></View><View style={s.coin}><Text style={s.coinText}>C</Text></View></View>
    <CollectionSectionTabs active="CollectionHistory" navigate={navigate}/>
    <View style={s.timeline}>{events.length ? events.map((event,index)=>{const positive=!String(event.type).includes("removed");const name=event.name||event.binderName||event.milestoneTitle||"Collection";return <View key={event.id||index} style={s.event}><View style={[s.dot,{backgroundColor:positive?colors.purple:colors.red}]}/><View style={s.eventBody}><Text style={s.eventTitle}>{LABELS[event.type]||"Updated"} {name}</Text><Text style={s.eventMeta}>{event.finish||event.note||"Collection registry updated"}</Text><Text style={s.date}>{event.timestamp?new Date(event.timestamp).toLocaleString():"Recently"}</Text></View>{event.newValue!==undefined&&<Text style={[s.change,!positive&&s.negative]}>{positive?"+":""}{event.newValue}</Text>}</View>}) : <View style={s.emptyCard}><Text style={s.emptyTitle}>No registry history yet</Text><Text style={s.emptyText}>Card additions, binder milestones and vault activity will appear here automatically.</Text></View>}</View>
  </ScrollView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.bg},content:{paddingTop:24,paddingBottom:36},heading:{paddingHorizontal:24,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},title:{color:colors.text,fontSize:34,fontWeight:"800"},kicker:{color:colors.purple,fontSize:11,fontWeight:"800",letterSpacing:1.35,marginTop:4},coin:{width:44,height:44,borderRadius:22,borderWidth:1.5,borderColor:colors.purple,alignItems:"center",justifyContent:"center"},coinText:{color:colors.purple,fontWeight:"800",fontSize:14},timeline:{marginHorizontal:24,marginTop:24,paddingLeft:19,borderLeftWidth:1,borderLeftColor:colors.border},event:{minHeight:106,borderBottomWidth:1,borderBottomColor:colors.border,flexDirection:"row",alignItems:"flex-start",paddingVertical:18},dot:{position:"absolute",left:-25,top:23,width:11,height:11,borderRadius:6},eventBody:{flex:1},eventTitle:{color:colors.text,fontSize:15,fontWeight:"800",lineHeight:20},eventMeta:{color:colors.textSecondary,fontSize:11,lineHeight:16,marginTop:5},date:{color:colors.textTertiary,fontSize:9,marginTop:7},change:{color:colors.purple,fontSize:10,fontWeight:"800",backgroundColor:colors.purpleSoft,paddingHorizontal:8,paddingVertical:5,borderRadius:6,marginLeft:8},negative:{color:colors.red},emptyCard:{marginLeft:-19,padding:21,borderRadius:16,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},emptyTitle:{color:colors.text,fontSize:18,fontWeight:"800"},emptyText:{color:colors.textSecondary,fontSize:12,lineHeight:18,marginTop:8}});
