import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, ScrollView } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useAppContext } from '../AppContext';
import { colors } from '../theme';
const TYPES = ['Fire 🔥','Water 💧','Grass 🍃','Lightning ⚡','Psychic 🔮']; const LEVELS = ['Novice','Intermediate','Elite Expert']; const AVATARS = ['#2C1F04','#18253A','#2D162D','#163125'];
export default function CompleteProfileScreen({ navigate, goBack }) { const { updateUserProfile } = useAppContext(); const [displayName,setDisplayName]=useState(''); const [favoriteType,setFavoriteType]=useState('Lightning ⚡'); const [level,setLevel]=useState('Elite Expert'); const [avatar,setAvatar]=useState(0); const finish=()=>{updateUserProfile({displayName:displayName.trim(),favoriteType,collectorLevel:level});navigate('Onboarding');}; return <ScrollView style={styles.screen} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><TouchableOpacity style={styles.back} onPress={goBack}><Ionicons name="chevron-back" size={16} color="#F4F4F5" /></TouchableOpacity><View><Text style={styles.eyebrow}>TRAINER REGISTRY</Text><Text style={styles.title}>Complete Profile</Text></View></View><View style={styles.body}><TouchableOpacity style={styles.avatarPicker} onPress={()=>setAvatar((value)=>(value+1)%AVATARS.length)}><View style={[styles.avatar,{backgroundColor:AVATARS[avatar]}]}><Ionicons name="camera-outline" size={32} color={colors.purple} /></View><View style={styles.addPill}><Text style={styles.addText}>ADD</Text></View></TouchableOpacity><View style={styles.field}><Text style={styles.label}>TRAINER USERNAME</Text><TextInput value={displayName} onChangeText={setDisplayName} placeholder="AshKetchum" placeholderTextColor="#71717A" style={styles.input} /></View><Selector label="FAVORITE POKÉMON SPECIALTY" values={TYPES} selected={favoriteType} onSelect={setFavoriteType} wrap /><Selector label="COLLECTOR LEVEL" values={LEVELS} selected={level} onSelect={setLevel} /><TouchableOpacity style={[styles.primary,!displayName.trim()&&styles.disabled]} disabled={!displayName.trim()} onPress={finish}><Text style={styles.primaryText}>Complete Setup</Text></TouchableOpacity></View></ScrollView>; }
const Selector=({label,values,selected,onSelect,wrap})=><View style={styles.selector}><Text style={styles.label}>{label}</Text><View style={[styles.options,wrap&&styles.wrap]}>{values.map((value)=><TouchableOpacity key={value} style={[styles.chip,!wrap&&styles.level,selected===value&&styles.chipActive]} onPress={()=>onSelect(value)}><Text style={[styles.chipText,selected===value&&styles.chipTextActive]}>{value}</Text></TouchableOpacity>)}</View></View>;
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#080808'},content:{paddingBottom:24,justifyContent:'center',flexGrow:1},header:{height:64,marginHorizontal:24,flexDirection:'row',alignItems:'center',gap:16},back:{width:36,height:36,borderRadius:12,borderWidth:1,borderColor:'rgba(255,255,255,0.08)',backgroundColor:'#121212',alignItems:'center',justifyContent:'center'},eyebrow:{color:'#A1A1AA',fontSize:11,fontWeight:'500'},title:{color:'#F4F4F5',fontSize:22,fontWeight:'600',marginTop:2},body:{paddingHorizontal:24,gap:20},avatarPicker:{height:98,alignItems:'center',justifyContent:'flex-start'},avatar:{width:90,height:90,borderRadius:45,borderWidth:2,borderColor:'rgba(212,175,55,0.25)',alignItems:'center',justifyContent:'center'},addPill:{position:'absolute',bottom:0,left:'57%',backgroundColor:'#D4AF37',borderRadius:6,paddingHorizontal:8,paddingVertical:4},addText:{color:'#080808',fontSize:10,fontWeight:'700'},field:{gap:8},label:{color:'#A1A1AA',fontSize:11,fontWeight:'500'},input:{height:48,borderRadius:12,borderWidth:1,borderColor:'rgba(255,255,255,0.08)',backgroundColor:'#121212',paddingHorizontal:16,color:'#F4F4F5',fontSize:14},selector:{gap:8},options:{flexDirection:'row',gap:8},wrap:{flexWrap:'wrap'},chip:{borderRadius:10,borderWidth:1,borderColor:'rgba(255,255,255,0.08)',backgroundColor:'#121212',paddingHorizontal:12,paddingVertical:8},level:{flex:1,alignItems:'center',paddingHorizontal:4,paddingVertical:12,borderRadius:12},chipActive:{borderColor:'#D4AF37',backgroundColor:'rgba(212,175,55,0.12)'},chipText:{color:'#F4F4F5',fontSize:13,fontWeight:'500'},chipTextActive:{color:'#D4AF37'},primary:{height:48,borderRadius:14,backgroundColor:'#D4AF37',alignItems:'center',justifyContent:'center',marginTop:8},disabled:{opacity:.42},primaryText:{color:'#080808',fontSize:14,fontWeight:'600'}});
