import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, KeyboardAvoidingView, Platform } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { supabase } from '../lib/supabase';
export default function ForgotPasswordScreen({ navigate, goBack }) {
  const [email, setEmail] = useState(''); const [loading, setLoading] = useState(false); const [authError, setAuthError] = useState('');
  const sendReset = async () => { setLoading(true); setAuthError(''); const normalizedEmail = email.trim().toLowerCase(); const { error } = await supabase.auth.resetPasswordForEmail(normalizedEmail, { redirectTo: 'pokefile://reset-password' }); setLoading(false); if (error) { setAuthError(error.message); return; } navigate('PasswordResetEmailSent', { email: normalizedEmail }); };
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.body}><View style={styles.header}><TouchableOpacity style={styles.backButton} onPress={goBack}><Ionicons name="chevron-back" size={16} color="#F4F4F5" /></TouchableOpacity><View><Text style={styles.eyebrow}>ACCOUNT RECOVERY</Text><Text style={styles.title}>Reset Password</Text></View></View><Text style={styles.guidance}>Enter the email address tied to your trainer index. We will send a secure validation link to recover your account access.</Text><View style={styles.field}><Text style={styles.label}>REGISTERED EMAIL</Text><TextInput value={email} onChangeText={setEmail} placeholder="Enter your email address" placeholderTextColor="#71717A" style={[styles.input, email.length > 0 && styles.activeInput]} autoCapitalize="none" keyboardType="email-address" /></View><View style={styles.actions}><TouchableOpacity style={[styles.primary, (!email.trim() || loading) && styles.disabled]} disabled={!email.trim() || loading} onPress={sendReset}><Text style={styles.primaryText}>{loading ? 'Sending…' : 'Send Reset Link'}</Text></TouchableOpacity>{authError ? <Text style={styles.error}>{authError}</Text> : null}<View style={styles.inline}><Text style={styles.muted}>Remembered password?</Text><TouchableOpacity onPress={() => navigate('SignIn')}><Text style={styles.gold}>Sign In</Text></TouchableOpacity></View></View></View></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#080808', justifyContent: 'center' }, body: { paddingHorizontal: 24, gap: 24 }, header: { height: 64, paddingHorizontal: 24, paddingTop: 16, paddingBottom: 8, flexDirection: 'row', alignItems: 'center', gap: 16 }, backButton: { width: 36, height: 36, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', backgroundColor: '#121212', alignItems: 'center', justifyContent: 'center' }, eyebrow: { color: '#A1A1AA', fontSize: 11, fontWeight: '500' }, title: { color: '#F4F4F5', fontSize: 22, fontWeight: '600', marginTop: 2 }, guidance: { color: '#A1A1AA', fontSize: 14, lineHeight: 21 }, field: { gap: 8 }, label: { color: '#A1A1AA', fontSize: 12, fontWeight: '500' }, input: { height: 48, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', paddingHorizontal: 16, color: '#F4F4F5', fontSize: 14 }, activeInput: { borderColor: '#D4AF37', backgroundColor: 'rgba(255,255,255,0.02)' }, actions: { gap: 16 }, primary: { height: 48, borderRadius: 14, backgroundColor: '#D4AF37', alignItems: 'center', justifyContent: 'center' }, disabled: { opacity: 0.42 }, primaryText: { color: '#080808', fontSize: 14, fontWeight: '600' }, inline: { flexDirection: 'row', justifyContent: 'center', gap: 6 }, muted: { color: '#A1A1AA', fontSize: 13 }, gold: { color: '#D4AF37', fontSize: 13, fontWeight: '600' }, error: { color: '#E45D5D', fontSize: 12, textAlign: 'center' },
});
