import React from "react";
import { Image, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { colors } from "../theme";
import { CARD_LIBRARY } from "../data";
import CollectionSectionTabs from "../components/CollectionSectionTabs";

export default function MyCollectionScreen({ navigate, collectionQuantities = {}, binders = [], wishlistItems = [], vaultAssets = [] }) {
  const owned = CARD_LIBRARY.filter((card) => Number(collectionQuantities[card.id] || 0) > 0);
  const quantity = owned.reduce((sum, card) => sum + Number(collectionQuantities[card.id] || 0), 0);
  const cardValue = owned.reduce((sum, card) => sum + Number(card.value || 0) * Number(collectionQuantities[card.id] || 0), 0);
  const vaultValue = vaultAssets.reduce((sum, asset) => sum + Number(asset.marketValue || asset.value || 0) * Number(asset.quantity || 1), 0);
  const highest = [...owned].sort((a, b) => Number(b.value || 0) - Number(a.value || 0))[0];
  return <ScrollView style={s.page} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <View style={s.heading}><View><Text style={s.title}>My Registry</Text><Text style={s.kicker}>INDEX VALUE METRICS</Text></View><View style={s.coin}><Text style={s.coinText}>C</Text></View></View>
    <CollectionSectionTabs active="MyCollection" navigate={navigate}/>
    <View style={s.hero}><Text style={s.micro}>ESTIMATED PORTFOLIO VALUE</Text><Text style={s.value}>€{(cardValue + vaultValue).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</Text><View style={s.divider}/><View style={s.heroStats}><Metric label="TOTAL CARDS" value={`${quantity} Owned`}/><Metric label="GRADED COPIES" value={`${vaultAssets.filter((a)=>a.type === "graded").length} Graded`} accent/></View></View>
    <Text style={s.section}>QUICK ACCESS</Text><View style={s.quickGrid}><Quick label="All Cards" meta={`${owned.length} items tracked`} icon="▣" onPress={()=>navigate("CollectionAll")}/><Quick label="Binders" meta={`${binders.length} custom sets`} icon="▥" onPress={()=>navigate("Binders")}/><Quick wide label="Registry Wishlist" meta={`${wishlistItems.length} priority chases`} icon="♡" onPress={()=>navigate("Wishlist")}/></View>
    {highest && <TouchableOpacity style={s.highest} onPress={()=>navigate("CardDetail",{cardId:highest.id})}><Text style={s.highestLabel}>HIGHEST VALUED SPECIMEN</Text><View style={s.highestRow}><Image source={{uri:highest.image}} style={s.thumb}/><View style={s.highestInfo}><Text style={s.highestName}>{highest.name}</Text><Text style={s.cardMeta}>{highest.setName} · #{highest.number}</Text><Text style={s.grade}>RAW</Text></View><Text style={s.highestValue}>€{Number(highest.value||0).toFixed(2)}</Text></View></TouchableOpacity>}
  </ScrollView>;
}
function Metric({label,value,accent}){return <View><Text style={s.micro}>{label}</Text><Text style={[s.metricValue,accent&&s.accent]}>{value}</Text></View>}
function Quick({label,meta,icon,onPress,wide}){return <TouchableOpacity style={[s.quick,wide&&s.quickWide]} onPress={onPress}><View style={s.quickIcon}><Text style={s.quickIconText}>{icon}</Text></View><View><Text style={s.quickLabel}>{label}</Text><Text style={s.quickMeta}>{meta}</Text></View></TouchableOpacity>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.bg},content:{paddingTop:24,paddingBottom:34},heading:{paddingHorizontal:24,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},title:{color:colors.text,fontSize:34,fontWeight:"800"},kicker:{color:colors.purple,fontSize:11,fontWeight:"800",letterSpacing:1.35,marginTop:4},coin:{width:44,height:44,borderRadius:22,borderWidth:1.5,borderColor:colors.purple,alignItems:"center",justifyContent:"center"},coinText:{color:colors.purple,fontWeight:"800",fontSize:15},hero:{marginHorizontal:24,marginTop:18,padding:20,borderRadius:18,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},micro:{color:colors.textTertiary,fontSize:10,fontWeight:"700",letterSpacing:.55},value:{color:colors.text,fontSize:38,fontWeight:"800",marginTop:8},divider:{height:1,backgroundColor:colors.border,marginVertical:16},heroStats:{flexDirection:"row",justifyContent:"space-between"},metricValue:{color:colors.text,fontSize:17,fontWeight:"800",marginTop:5},accent:{color:colors.purple},section:{marginHorizontal:24,color:colors.textSecondary,fontSize:12,fontWeight:"800",marginTop:20,marginBottom:9},quickGrid:{paddingHorizontal:24,flexDirection:"row",flexWrap:"wrap",gap:9},quick:{width:"48.5%",minHeight:78,borderRadius:15,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,padding:13,flexDirection:"row",alignItems:"center",gap:11},quickWide:{width:"100%"},quickIcon:{width:36,height:36,borderRadius:10,backgroundColor:colors.purpleSoft,alignItems:"center",justifyContent:"center"},quickIconText:{color:colors.purple,fontSize:20},quickLabel:{color:colors.text,fontSize:13,fontWeight:"700"},quickMeta:{color:colors.textTertiary,fontSize:9,marginTop:4},highest:{marginHorizontal:24,marginTop:18,padding:15,borderRadius:17,borderWidth:1.5,borderColor:colors.purple,backgroundColor:colors.surface},highestLabel:{color:colors.purple,fontSize:10,fontWeight:"800"},highestRow:{flexDirection:"row",alignItems:"center",marginTop:11},thumb:{width:59,height:80,borderRadius:6,backgroundColor:colors.card},highestInfo:{flex:1,marginLeft:13},highestName:{color:colors.text,fontSize:15,fontWeight:"800"},cardMeta:{color:colors.textTertiary,fontSize:10,marginTop:4},grade:{alignSelf:"flex-start",color:colors.bg,backgroundColor:colors.purple,fontSize:8,fontWeight:"800",paddingHorizontal:6,paddingVertical:3,borderRadius:4,marginTop:6},highestValue:{color:colors.purple,fontSize:15,fontWeight:"800"}});
