import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, KeyboardAvoidingView, Platform } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { supabase } from '../lib/supabase';
export default function ResetPasswordScreen({ navigate, goBack }) {
  const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [authError, setAuthError] = useState('');
  const score = [password.length >= 8, /[0-9]/.test(password), /[A-Z]/.test(password), /[^A-Za-z0-9]/.test(password)].filter(Boolean).length; const canSubmit = score >= 3 && password === confirm;
  const updatePassword = async () => { setLoading(true); setAuthError(''); const { error } = await supabase.auth.updateUser({ password }); setLoading(false); if (error) { setAuthError(error.message); return; } navigate('PasswordResetSuccessful'); };
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><TouchableOpacity style={styles.back} onPress={goBack}><Ionicons name="chevron-back" size={16} color="#F4F4F5" /></TouchableOpacity><View><Text style={styles.eyebrow}>VAULT PROTECTION</Text><Text style={styles.title}>Reset Password</Text></View></View><View style={styles.body}><View style={styles.inputs}><PasswordField label="NEW PASSWORD" value={password} onChangeText={setPassword} show={showPassword} toggle={() => setShowPassword((value) => !value)} /><PasswordField label="CONFIRM NEW PASSWORD" value={confirm} onChangeText={setConfirm} show={showPassword} toggle={() => setShowPassword((value) => !value)} /></View><View style={styles.strength}><View style={styles.strengthHeader}><Text style={styles.muted}>Password Strength:</Text><Text style={styles.gold}>{score >= 3 ? 'Strong' : score === 2 ? 'Medium' : 'Weak'}</Text></View><View style={styles.bars}>{[1,2,3,4].map((value) => <View key={value} style={[styles.bar, value <= score && styles.barActive]} />)}</View><Text style={styles.hint}>Requires at least 8 characters, including numbers and uppercase letters.</Text></View><TouchableOpacity style={[styles.primary, (!canSubmit || loading) && styles.disabled]} disabled={!canSubmit || loading} onPress={updatePassword}><Text style={styles.primaryText}>{loading ? 'Updating…' : 'Update Password'}</Text></TouchableOpacity>{authError ? <Text style={styles.error}>{authError}</Text> : null}</View></KeyboardAvoidingView>;
}
const PasswordField = ({ label, value, onChangeText, show, toggle }) => <View style={styles.field}><Text style={styles.label}>{label}</Text><View style={styles.inputBox}><TextInput value={value} onChangeText={onChangeText} secureTextEntry={!show} style={styles.input} placeholder="Enter secure password" placeholderTextColor="#71717A" autoCapitalize="none" /><TouchableOpacity onPress={toggle}><Ionicons name={show ? 'eye-off-outline' : 'eye-outline'} size={16} color="#A1A1AA" /></TouchableOpacity></View></View>;
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#080808', justifyContent: 'center' }, header: { height: 64, marginHorizontal: 24, flexDirection: 'row', alignItems: 'center', gap: 16 }, back: { width: 36, height: 36, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', backgroundColor: '#121212', alignItems: 'center', justifyContent: 'center' }, eyebrow: { color: '#A1A1AA', fontSize: 11, fontWeight: '500' }, title: { color: '#F4F4F5', fontSize: 22, fontWeight: '600', marginTop: 2 }, body: { paddingHorizontal: 24, paddingBottom: 32, gap: 24 }, inputs: { gap: 16 }, field: { gap: 8 }, label: { color: '#A1A1AA', fontSize: 11, fontWeight: '500' }, inputBox: { height: 48, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', backgroundColor: '#121212', paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 12 }, input: { flex: 1, color: '#F4F4F5', fontSize: 14 }, strength: { gap: 8 }, strengthHeader: { flexDirection: 'row', justifyContent: 'space-between' }, muted: { color: '#A1A1AA', fontSize: 12 }, gold: { color: '#D4AF37', fontSize: 12, fontWeight: '600' }, bars: { height: 4, flexDirection: 'row', gap: 6 }, bar: { flex: 1, borderRadius: 2, backgroundColor: '#27272A' }, barActive: { backgroundColor: '#D4AF37' }, hint: { color: '#A1A1AA', fontSize: 11 }, primary: { height: 48, borderRadius: 14, backgroundColor: '#D4AF37', alignItems: 'center', justifyContent: 'center', marginTop: 8 }, disabled: { opacity: 0.42 }, primaryText: { color: '#080808', fontSize: 14, fontWeight: '600' }, error: { color: '#E45D5D', fontSize: 12, textAlign: 'center' } });
